site_name: RAG Chatbot Documentation
site_description: Documentation for RAG-enabled chatbot using Clean Architecture
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("../")
          selection:
            members: true
          rendering:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Architecture:
    - Overview: architecture/overview.md
    - Domain Layer: architecture/domain-layer.md
    - Application Layer: architecture/application-layer.md
    - Infrastructure Layer: architecture/infrastructure-layer.md
    - Presentation Layer: architecture/presentation-layer.md
  - API Reference:
    - REST API: api/rest-api.md
    - Python API: api/python-api.md
  - Usage Guides:
    - Chat Interface: guides/chat-interface.md
    - Document Management: guides/document-management.md
    - RAG Configuration: guides/rag-configuration.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Code Style: development/code-style.md
  - Deployment:
    - Production Setup: deployment/production-setup.md
    - Monitoring: deployment/monitoring.md
    - Scaling: deployment/scaling.md